### ISSUE TITLE
Community provider list

### ISSUE THREAD

**Issue by blkperl** [Yelp/terraform-provider-signalform#11]
I suggest filling out the form and getting the project added to the community index so that this project receives more visibility. I only knew to search for it because of SignalFX support and it's a much better option than the [signalfx-detector-syncer](https://github.com/signalfx/signalfx-detector-syncer) tool.

https://www.terraform.io/docs/providers/type/community-index.html

**Comment by poros** [comment]
That's a great idea! I didn't even know that page existed. Will do

**Comment by poros** [comment]
I submitted the form for registration. Let's wait to hear it back from HashiCorp.

**Comment by dichiarafrancesco** [comment]
Thanks @blkperl +1 ! and thanks @poros for taking care of it

**Comment by bronislav** [comment]
@poros Any updates on this?

**Comment by poros** [comment]
Nope. They never got back to me... :'(

**Comment by ajwood-acquia** [comment]
Looks like it's listed now, this issue can probably be closed.

https://www.terraform.io/docs/providers/type/community-index.html

**Comment by poros** [comment]
@ajwood-acquia thanks for reporting! I honestly lost hope :P
