### ISSUE TITLE
Suggestion: Docker build

### ISSUE THREAD

**Issue by jfharden** [Yelp/terraform-provider-signalform#13]
Before I do the work to implement it I wondered if you would be open to me providing a PR which adds a Dockerfile to this project to allow building in a docker container instead of needing build tools installed locally?

I would also propose to add a `make docker` target which will run the necessary docker commands to build the provider.

**Comment by poros** [comment]
I am sorry, I am a bit confused. The project already supports the project to be built inside Docker; the Dockerfile is in the build folder. To run it either use `make package` or `make itest_DISTRO` (lucid, trusty and xenial are supported)

**Comment by jfharden** [comment]
Gah sorry! Long day and somehow I totally missed that. Thanks for the great provider anywho.
