### ISSUE TITLE
Visualization options for detector

### ISSUE THREAD

**Issue by bronislav** [Yelp/terraform-provider-signalform#15]
Hi!

I'm trying to create detector chart and could not find a way to add visualization options (color metrics with different colors, units etc.). I see this options available on the chart.

Maybe there is a way to create a chart and then reference chart in the detector resource. Any suggestions?

**Comment by kokje** [comment]
The SignalFx Detector API only allows time range and data markers as visualization options
https://developers.signalfx.com/reference#section-visualizationoptions-model

Any changes to the Detector Model need to be made by SignalFx. As a workaround maybe you can specify a link to the chart in the rule metadata (parameterized_body, tip or runbook_url fields). That way when the detector fires you can access the chart through the alert.

**Comment by bronislav** [comment]
Thank you, for an explanation.
