### ISSUE TITLE
Add ability to configure provider using .netrc file

### ISSUE THREAD

**Issue by bronislav** [Yelp/terraform-provider-signalform#16]
The `.netrc` file is quite a common way to handle authentication credentials for any host.

We are using this way for handling auth credentials for various machines in our network.

Is it planned to add `.netrc` support?

**Comment by poros** [comment]
I don't think we use it in our organization, so no, we do not have any plan to add support for it. But pull requests are welcome, if you want to give it a shot and such a change is backward compatible.

**Comment by raghunat** [comment]
@bronislav want to try my fork before I go any further?

**Comment by poros** [comment]
Closed by #17
