### ISSUE TITLE
Support Tags and Teams for Detectors

### ISSUE THREAD

**Issue by bplotnick** [Yelp/terraform-provider-signalform#3]
The SignalFlow [detector model](https://developers.signalfx.com/v2/reference#section-detector-model) supports tags and teams, but signalform doesn't seem to support it

**Comment by poros** [comment]
@bplotnick the PR above adds exactly what you asked, even though "real" support for teams (creation, update, etc) is not in signalform yet and tags are not discoverable via signalform-tools.

**Comment by bplotnick** [comment]
@poros Awesome, thanks! Closing
